services:
  db:
    image: postgres:15-alpine
    container_name: loot_kingdom_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lootpassword123
      POSTGRES_DB: lootkingdom
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: